/* State-wise hidden gems for Explore search. */
window.SARTHI_HIDDEN_GEMS = {
  "Andhra Pradesh": "Gandikota|Belum Caves|Lepakshi|Araku Valley|Borra Caves|Papikondalu|Horsley Hills|Talakona Waterfalls|Maredumilli|Lambasingi|Konaseema|Pulicat Lake|Uppada|Kondapalli|Srisailam forests|Rollapadu Wildlife Sanctuary|Ahobilam|Dindi|Yanam|Chandragiri",
  "Arunachal Pradesh": "Mechuka|Ziro Valley|Dong Village|Anini|Tawang's lesser-known villages|Sangti Valley|Dirang|Mandala Top|Zemithang|Bum La|Shonga-tser Lake|Mayudia|Walong|Kibithu|Tuting|Yingkiong|Mechuka villages|Namdapha|Pangsau Pass|Talley Valley|Bomdila",
  "Assam": "Haflong|Majuli|Mayong|Hoollongapar Gibbon Sanctuary|Pobitora|Kakochang Waterfalls|Panimur|Chandubi Lake|Dibru-Saikhowa|Dehing Patkai|Sivasagar|Digboi|Dima Hasao|Umrangso|Jatinga|Garbhanga Reserve Forest|Orang National Park|Manas lesser-known villages|Bogamati|Bhairabkunda",
  "Bihar": "Valmiki Nagar|Vikramshila|Rajgir hills|Pawapuri|Kakolat Waterfall|Telhar Kund|Barabar Caves|Kesaria Stupa|Mandar Hill|Simultala|Bhimbandh Wildlife Sanctuary|Kanwar Lake|Rajgir Nature Safari|Lauriya Nandangarh|Sonepur|Madhubani villages|Gaya's rural Buddhist sites|Rohtas Plateau|Kaimur Wildlife Sanctuary|Buxar's heritage sites",
  "Chhattisgarh": "Chitrakote Falls|Tirathgarh Falls|Kanger Valley|Kutumsar Caves|Kailash Gufa|Mainpat|Tamnar|Sirpur|Barnawapara|Achanakmar|Amarkantak surroundings|Malhar|Bhoramdeo|Dantewada|Bailadila|Tirathgarh forests|Koriya|Gangrel|Sitanadi Wildlife Sanctuary|Udanti Wildlife Sanctuary",
  "Goa": "Netravali|Cotigao Wildlife Sanctuary|Chorla Ghats|Galgibaga Beach|Butterfly Beach|Kakolem Beach|Cola Beach|Talpona|Agonda's quieter side|Divar Island|Chorao Island|Fontainhas|Usgalimal rock art|Tambdi Surla|Dudhsagar's surrounding trails|Arvalem Caves|Harvalem Falls|Mollem|Canacona|Saligao",
  "Gujarat": "Dholavira|Polo Forest|Saputara|Little Rann of Kutch|Zinzuwada|Modhera's surrounding villages|Lothal|Champaner-Pavagadh|Pavagadh forests|Narara Marine National Park|Shivrajpur Beach|Mandvi|Kutch villages|Hodka|Nirona|Dhordo|Kalo Dungar|Chhari-Dhand|Jessore Sloth Bear Sanctuary|Wilson Hills",
  "Haryana": "Morni Hills|Tikkar Tal|Kalesar National Park|Damdama Lake|Sultanpur National Park|Pinjore Gardens|Sohna|Farrukhnagar|Nahar Singh Mahal|Rakhigarhi|Agroha|Banawali|Surajkund|Tosham Hills|Loharu Fort|Chhachhrauli|Hathnikund|Khaparwas Wildlife Sanctuary|Bhindawas|Abhimanyupur",
  "Himachal Pradesh": "Pabbar Valley|Jibhi|Shoja|Barot|Chitkul|Kalpa|Rakcham|Sangla Valley|Chanshal|Tirthan Valley|Sainj Valley|Fojal|Karsog|Janjehli|Pangi Valley|Miyar Valley|Spiti's Langza|Pin Valley|Kibber|Hikkim|Dhankar|Chitkul villages|Prashar Lake|Chandratal|Tosh|Malana",
  "Jharkhand": "Netarhat|Betla National Park|Lodh Falls|Dassam Falls|Hundru Falls|Jonha Falls|Patratu Valley|McCluskieganj|Deoghar|Parasnath|Dalma Wildlife Sanctuary|Hazaribagh|Usri Falls|Rajrappa|Saranda Forest|Amadubi|Maluti|Palamau|Dimna Lake|Tagore Hill",
  "Karnataka": "Agumbe|Gokarna's quieter beaches|Kudremukh|Kodachadri|Sakleshpur|Honnemaradu|Dandeli|Yana Caves|Maravanthe|St. Mary's Island|Badami surroundings|Banavasi|Sirsi|Jog Falls surroundings|Devbagh|Kavaledurga|Skandagiri|Bheemeshwari|BR Hills|Kyatanamakki|Galageshwara|Hampi's rural side",
  "Kerala": "Kanthalloor|Valiyaparamba|Vagamon|Ponmudi|Thenmala|Gavi|Silent Valley|Marayoor|Munroe Island|Kumbalangi|Kuttanad villages|Meesapulimala|Illikkal Kallu|Paithalmala|Ranipuram|Bekal's lesser-known surroundings|Aruvikkuzhi|Nelliyampathy|Athirappilly's surrounding forests|Thattekad",
  "Madhya Pradesh": "Madla|Orchha|Mandu|Pachmarhi|Tamia|Patalkot|Amarkantak|Chanderi|Maheshwar|Bawangaja|Bhimbetka|Panna|Ken Gharial Sanctuary|Tawa|Sailana|Kuno|Burhanpur|Morena|Bateshwar|Raneh Falls|Hanumantiya",
  "Maharashtra": "Bhandardara|Kaas Plateau|Tarkarli|Amboli|Malshej Ghat|Tamhini Ghat|Harishchandragad|Sandhan Valley|Lonar Lake|Jawhar|Saputara-border villages|Bhimashankar|Kalsubai|Naneghat|Rajmachi|Korigad|Karnala|Ratangad|Velas|Harihareshwar|Guhagar|Dapoli|Sindhudurg villages|Phansad Wildlife Sanctuary",
  "Manipur": "Loktak's lesser-known islands|Andro|Shirarakhong|Dzuko Valley approach|Khongjom|Keibul Lamjao surroundings|Sendra|Moirang|Thanga Island|Karong|Sadu Chiru Waterfall|Koubru|Tamenglong|Barak Waterfalls|Zeiladzang|Ukhrul|Shirui Hills|Kachai|Jessami|Yangkhullen",
  "Meghalaya": "Nongriat|Mawlynnong|Mawphlang|Laitlum Canyon|Krang Suri|Shnongpdeng|Dawki's surrounding villages|Nongkhnum Island|Wei Sawdong|Nohkalikai's surrounding trails|Mawsynram|Krem Puri|Syntung|Phe Phe Falls|Lyngksiar Falls|Dainthlen Falls|Tyrshi Falls|Nartiang|Jowai|Sohra's hidden villages",
  "Mizoram": "Reiek|Hmuifang|Phawngpui|Vantawng Falls|Thenzawl|Champhai|Zokhawthar|Durtlang|Tam Dil|Serchhip|Lunglei|Saiha|Palak Lake|Blue Mountain National Park|Murlen National Park|Falkawn|Sialsuk|Khawzawl|Tawi|Lengteng Wildlife Sanctuary",
  "Nagaland": "Dzükou Valley|Khonoma|Mokokchung|Longwa|Mon|Shilloi Lake|Pfutsero|Japfü|Benreu|Tuophema|Satoi|Intangki|Kachari Ruins|Meluri|Phek|Wokha|Mount Pauna|Doyang|Sukhajan|Tseminyu",
  "Odisha": "Deomali|Satkosia|Daringbadi|Chandipur|Gopalpur|Mahendragiri|Koraput|Rayagada|Taptapani|Jirang|Similipal|Barehipani Falls|Bhitarkanika|Chilika's lesser-known islands|Mangalajodi|Raghurajpur|Pipili|Dhauli's rural surroundings|Ratnagiri|Udayagiri|Lalitgiri|Barunei|Khandadhar Falls",
  "Punjab": "Kanjli Wetland|Harike Wetland|Ropar Wetland|Nangal Wetland|Takhni-Rehmapur Wildlife Sanctuary|Dholbaha|Ransar|Qila Mubarak, Bathinda|Mubarakpur|Shahpur Kandi|Ranjit Sagar Lake|Anandpur Sahib's surrounding hills|Kiratpur Sahib|Hussainiwala|Abohar Wildlife Sanctuary|Chhapar Wildlife Sanctuary|Muktsar|Kapurthala heritage sites|Sultanpur Lodhi|Sainik School Kila Raipur",
  "Rajasthan": "Osian|Bundi|Barmer|Kuldhara|Jawai|Khimsar|Bishnoi villages|Menal|Bhangarh|Abhaneri|Chand Baori|Dholpur|Karauli|Baroli|Deogarh|Kumbhalgarh's rural region|Mount Abu's quieter trails|Sambhar Lake|Tal Chhapar|Desert villages around Jaisalmer|Ranakpur|Ghanerao|Shahabad|Alwar's hidden forts",
  "Sikkim": "Dzongu|Zuluk|Ravangla|Temi|Yuksom|Borang|Hee Gaon|Khecheopalri|Rinchenpong|Pelling's surrounding villages|Lachung|Yumthang's remote trails|Lachen|Gurudongmar surroundings|Tholung Valley|Uttarey|Aritar|Namchi|Samdruptse|Kabi Lungchok",
  "Tamil Nadu": "Valparai|Meghamalai|Kolli Hills|Yercaud|Jawadhu Hills|Pichavaram|Chettinad villages|Dhanushkodi|Vattakanal|Manjolai|Courtallam's lesser-known waterfalls|Kotagiri|Coonoor's quieter trails|Tharangambadi|Poompuhar|Gingee|Hogenakkal surroundings|Kalrayan Hills|Sathanur|Muthupet Mangroves|Javadi Hills",
  "Telangana": "Ananthagiri Hills|Laknavaram|Bogatha Waterfall|Ramappa surroundings|Pakhal Lake|Kawal Wildlife Sanctuary|Tadvai|Medaram|Pocharam|Kuntala Falls|Pochera Falls|Adilabad forests|Bhuvanagiri Fort|Koilkonda|Devarakonda|Farahabad|Nagarjuna Sagar's Telangana side|Singur|Domakonda Fort|Qutb Shahi rural heritage",
  "Tripura": "Jampui Hills|Unakoti|Neermahal|Sepahijala|Dumboor Lake|Pilak|Chabimura|Debtamura|Vanghmun|Jampui villages|Boxanagar|Trishna Wildlife Sanctuary|Rowa Wildlife Sanctuary|Udaipur|Matabari|Kamalasagar|Narikel Kunja|Gandacherra|Sabroom|Manu Valley",
  "Uttar Pradesh": "Chuka Beach|Chambal Safari|Saman Wildlife Sanctuary|Sandi Bird Sanctuary|Katarniaghat|Dudhwa|Sonbhadra|Chitrakoot|Bateshwar|Deogarh|Mahoba|Kalinjar|Sarnath's lesser-known sites|Mirzapur|Vindhyachal|Rajdari & Devdari Falls|Shuklaganj|Hastinapur|Kannauj|Surha Tal|Etawah Safari Park|Suhaildev Wildlife Sanctuary",
  "Uttarakhand": "Sarmoli|Munsiyari|Khirsu|Kanakchauri|Chopta|Pauri|Lansdowne|Jageshwar|Chaukori|Binsar|Dharchula|Abbott Mount|Peora|Didihat|Pangot|Ramgarh|Kanatal|Dhanaulti|Chakrata|Harshil|Nelang Valley|Mana's surrounding region|Pindari Glacier|Milam Valley",
  "West Bengal": "Buxa|Jaldapara|Dooars|Lava|Loleygaon|Pedong|Sillery Gaon|Tinchuley|Takdah|Chatakpur|Garpanchkot|Ayodhya Hills|Jhargram|Bishnupur|Mukutmanipur|Shantiniketan's rural side|Henry's Island|Bakkhali|Mousuni Island|Ganga Sagar's quieter areas|Kurseong|Mirik|Sandakphu|Singalila|Rajabhatkhawa",
  "Andaman & Nicobar Islands": "Baratang Island|Parrot Island|Long Island|North Passage Island|Cinque Island|Jolly Buoy Island|Ross & Smith Islands|Galathea Bay|Campbell Bay|Shyam Nagar|Chidiya Tapu|Mount Harriet|Rutland Island|Little Andaman",
  "Chandigarh": "Sukhna Lake's quieter trails|Kansal Forest|Nepli Forest|Siswan Forest|Terraced Garden|Japanese Garden|Leisure Valley|Botanical Garden|Burail Heritage sites",
  "Dadra & Nagar Haveli and Daman & Diu": "Dudhni Lake|Vanganga Garden|Satmaliya Deer Sanctuary|Kauncha|Bindrabin|Madhuban Dam|Devka Beach|Jampore Beach|Naida Caves|Fudam Bird Sanctuary|Ghoghla Beach|St. Jerome Fort",
  "Delhi": "Sanjay Van|Mehrauli Archaeological Park|Bhuli Bhatiyari Ka Mahal|Agrasen Ki Baoli|Jamali Kamali|Mirza Ghalib's Tomb|Hauz Khas Deer Park|Tughlaqabad Fort|Begumpur Mosque|Chirag Delhi|Majnu Ka Tilla",
  "Jammu & Kashmir": "Gurez Valley|Bangus Valley|Aharbal|Doodhpathri|Yusmarg|Lolab Valley|Sinthan Top|Warwan Valley|Keran|Chatpal|Dachigam|Kokernag|Achabal|Tarsar Marsar|Tulian Lake|Pahalgam's remote villages",
  "Ladakh": "Hanle|Turtuk|Dah-Hanu|Umling La|Phugtal Monastery|Zanskar Valley|Suru Valley|Shyok Valley|Saspul|Lamayuru's surrounding villages|Sumda Chun|Stok village|Khalsar|Panamik|Tso Moriri's remote areas",
  "Lakshadweep": "Bangaram|Thinnakara|Kadmat|Kalpeni|Kiltan|Chetlat|Bitra|Agatti's quieter areas|Minicoy|Suheli Par|Parali Islands",
  "Puducherry": "Paradise Beach's quieter side|Ousteri Lake|Arikamedu|Serenity Beach|Mahe|Yanam|Veerampattinam|Pichavaram nearby|Gingee surroundings|Auroville's lesser-known trails"
};

window.SARTHI_HIDDEN_GEM_IMAGES = {
  "Andhra Pradesh": "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=85",
  "Arunachal Pradesh": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=85",
  "Assam": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85",
  "Bihar": "https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=900&q=85",
  "Chhattisgarh": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=85",
  "Goa": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=85",
  "Gujarat": "https://images.unsplash.com/photo-1470214304380-aadaedcfff1b?auto=format&fit=crop&w=900&q=85",
  "Haryana": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85",
  "Himachal Pradesh": "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=85",
  "Jharkhand": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=85",
  "Karnataka": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=85",
  "Kerala": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85",
  "Madhya Pradesh": "https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=900&q=85",
  "Maharashtra": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=85",
  "Manipur": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=85",
  "Meghalaya": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=85",
  "Mizoram": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=85",
  "Nagaland": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=85",
  "Odisha": "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=85",
  "Punjab": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85",
  "Rajasthan": "https://images.unsplash.com/photo-1470214304380-aadaedcfff1b?auto=format&fit=crop&w=900&q=85",
  "Sikkim": "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=85",
  "Tamil Nadu": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=85",
  "Telangana": "https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=900&q=85",
  "Tripura": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=85",
  "Uttar Pradesh": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=900&q=85",
  "Uttarakhand": "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=85",
  "West Bengal": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=85",
  "Andaman & Nicobar Islands": "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=900&q=85",
  "Chandigarh": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85",
  "Dadra & Nagar Haveli and Daman & Diu": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=85",
  "Delhi": "https://images.unsplash.com/photo-1561361058-c24cecae35ca?auto=format&fit=crop&w=900&q=85",
  "Jammu & Kashmir": "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=85",
  "Ladakh": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=85",
  "Lakshadweep": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=85",
  "Puducherry": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=900&q=85"
};
