from sqlalchemy import JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.db.database import Base


class CulturalInformation(Base):
    """Curated cultural/historical information for a named landmark.

    Matched to a live OSM place at request time by normalized name (see
    app/services/cultural_service.py). This is intentionally NOT free-text
    generated by an LLM -- every row is written/reviewed content with a
    `sources` list, per the project's "no invented cultural facts" rule.
    """

    __tablename__ = "cultural_information"

    slug: Mapped[str] = mapped_column(String(200), primary_key=True)
    display_name: Mapped[str] = mapped_column(String(200))
    historical_significance: Mapped[str] = mapped_column(Text, default="")
    cultural_significance: Mapped[str] = mapped_column(Text, default="")
    architectural_significance: Mapped[str] = mapped_column(Text, default="")
    traditions: Mapped[str] = mapped_column(Text, default="")
    etiquette: Mapped[str] = mapped_column(Text, default="")
    visitor_guidance: Mapped[str] = mapped_column(Text, default="")
    sources: Mapped[list] = mapped_column(JSON, default=list)
